### ISSUE TITLE
bug encountered

### ISSUE THREAD

**Issue by zengguangjie** [ma-compbio/Higashi#10]
sorry to bother you again.
I got an exception like this when doing imputation:

> [ Epoch 0 of 60 ]
 - (Training) :   0%|                                                             | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/opt/service/Higashi-main/Code/main_cell.py", line 1164, in <module>
    load_first=False, save_embed=True, save_name="_stage1")
  File "/opt/service/Higashi-main/Code/main_cell.py", line 549, in train
    model, loss, training_data_generator, optimizer)
  File "/opt/service/Higashi-main/Code/main_cell.py", line 136, in train_epoch
    batch_edge_weight, batch_chrom, batch_to_neighs, y=batch_y)
  File "/opt/service/Higashi-main/Code/main_cell.py", line 47, in forward_batch_hyperedge
    pred, pred_var, pred_proba = model(x, (batch_chrom, batch_to_neighs))
  File "/opt/service/miniconda3/envs/higishi_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/service/Higashi-main/Code/Higashi_backend/Modules.py", line 737, in forward
    dynamic, static, attn = self.get_embedding(x, x_chrom)
  File "/opt/service/Higashi-main/Code/Higashi_backend/Modules.py", line 704, in get_embedding
    dynamic, static, attn = self.encode1(x, x, x_chrom, slf_attn_mask, non_pad_mask)
  File "/opt/service/miniconda3/envs/higishi_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/service/Higashi-main/Code/Higashi_backend/Modules.py", line 1136, in forward
    dynamic = self.pff_n1(dynamic) #* non_pad_mask
  File "/opt/service/miniconda3/envs/higishi_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/service/Higashi-main/Code/Higashi_backend/Modules.py", line 858, in forward
    output = self.w_stack[i](output)
  File "/opt/service/miniconda3/envs/higishi_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/service/miniconda3/envs/higishi_env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 298, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/service/miniconda3/envs/higishi_env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 295, in _conv_forward
    self.padding, self.dilation, self.groups)
TypeError: conv1d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)

I've done imputation on this dataset on another computer and it worked fine, but it goes wrong one this computer. Can you help me debug this problem? 
thank you for your time!

**Comment by ruochiz** [comment]
Hi,

Could you provide the version of Pytorch of the machine that encounters this bug?

**Comment by zengguangjie** [comment]
hi，
the version of Pytorch is 

> pytorch                   1.9.0           py3.7_cuda11.1_cudnn8.0.5_0    <unknown>

other software versions which might be helpful:

> cudatoolkit               11.1.1               h6406543_8    conda-forge
python                    3.7.9           hffdb5ce_100_cpython    conda-forge
numpy                     1.19.2                   pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi

thank you!

**Comment by ruochiz** [comment]
The bug comes with pytorch 1.9.0. I can run the code fine at pytorch 1.8.1 and encountered the same bug at 1.9.0. I updated a quick fix just minutes ago. I haven't test the whole program under 1.9.0 yet. If you encountered other bugs, feel free to post it here. Thanks.

**Comment by zengguangjie** [comment]
thank you for your help!
