### ISSUE TITLE
Error running Ramani data

### ISSUE THREAD

**Issue by mxw010** [ma-compbio/Higashi#34]
Hello,

After I installed higashi, I downloaded the ramani dataset ([this one](https://drive.google.com/drive/u/0/folders/1S0KOMAj60MxQP6mgPV1OKjn_J-lVpzKM)), json file and tried to run the analysis. 

```
config = "config_ramani.JSON"
higashi_model = Higashi(config)
higashi_model.process_data()
```

And get error:
```
generating start/end dict for chromosome
extracting from data.txt
generating contact maps for baseline
data loaded
4110311 False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gdstantonlab/mxw010/.conda/envs/higashi/lib/python3.9/site-packages/higashi-0.1.0a0-py3.9.egg/higashi/Higashi_wrapper.py", line 459, in process_data
    self.create_matrix()
  File "/home/gdstantonlab/mxw010/.conda/envs/higashi/lib/python3.9/site-packages/higashi-0.1.0a0-py3.9.egg/higashi/Higashi_wrapper.py", line 492, in create_matrix
    create_matrix(self.config)
  File "/home/gdstantonlab/mxw010/.conda/envs/higashi/lib/python3.9/site-packages/higashi-0.1.0a0-py3.9.egg/higashi/Process.py", line 549, in create_matrix
    bin_adj = pseudo_bulk()
  File "/home/gdstantonlab/mxw010/.conda/envs/higashi/lib/python3.9/site-packages/higashi-0.1.0a0-py3.9.egg/higashi/Process.py", line 539, in pseudo_bulk
    bin_adj = csr_matrix((temp_weight_mask, (
  File "/home/gdstantonlab/mxw010/.conda/envs/higashi/lib/python3.9/site-packages/scipy-1.7.3-py3.9-linux-x86_64.egg/scipy/sparse/compressed.py", line 54, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape,
  File "/home/gdstantonlab/mxw010/.conda/envs/higashi/lib/python3.9/site-packages/scipy-1.7.3-py3.9-linux-x86_64.egg/scipy/sparse/coo.py", line 196, in __init__
    self._check()
  File "/home/gdstantonlab/mxw010/.conda/envs/higashi/lib/python3.9/site-packages/scipy-1.7.3-py3.9-linux-x86_64.egg/scipy/sparse/coo.py", line 283, in _check
    raise ValueError('row index exceeds matrix dimensions')
ValueError: row index exceeds matrix dimensions
```

**Comment by ruochiz** [comment]
Hey, do you use the corresponding version of chrom.size/ cytoband.txt file? (The hg19 one)

**Comment by mxw010** [comment]
yup. that fixed it. Thanks.

**Comment by kevin-kas** [comment]
Where to get the chrom.size/ cytoband.txt file? On the google drive?

**Comment by kevin-kas** [comment]
Got it already
