### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by PeiKeGUO** [ma-compbio/Higashi#48]
Dear developers, I was running Ramani's code, and I replaced the data with my own. But I encountered the following error：

`[ Epoch 28 of 45 ]
- (Train)   bce:  0.2533, mse:  0.0000,  acc: 95.492 %, pearson: 0.852, spearman: 0.609, elapse: 27.909 s
- (Valid) bce:  0.2033,  acc: 98.862 %,pearson: 0.956, spearman: 0.644,elapse: 0.089 s
no improve: 1
[ Epoch 29 of 45 ]
- (Train)   bce:  0.2529, mse:  0.0000,  acc: 95.531 %, pearson: 0.854, spearman: 0.609, elapse: 26.552 s
- (Valid) bce:  0.2068,  acc: 98.737 %,pearson: 0.952, spearman: 0.643,elapse: 0.094 s
no improve: 2
[ Epoch 30 of 45 ]
- (Train)   bce:  0.2528, mse:  0.0000,  acc: 95.534 %, pearson: 0.854, spearman: 0.609, elapse: 26.419 s
- (Valid) bce:  0.2070,  acc: 98.739 %,pearson: 0.952, spearman: 0.644,elapse: 0.086 s
no improve: 3
[ Epoch 31 of 45 ]
- (Train)   bce:  0.2528, mse:  0.0000,  acc: 95.545 %, pearson: 0.854, spearman: 0.609, elapse: 27.653 s
- (Valid) bce:  0.2084,  acc: 98.711 %,pearson: 0.951, spearman: 0.643,elapse: 0.095 s
  - (Validation)   :  10%|█         | 1/10 [00:08<01:12,  8.09s/it]concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
    result_item = result_reader.recv()
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 355, in rebuild_storage_fd
    fd = df.detach()
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata
`'''`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data02/home/scv9147/run/24.3.21-higashi_K562_HAP1_500K.py", line 17, in <module>
    higashi_model.train_for_imputation_nbr_0()
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/site-packages/higashi/Higashi_wrapper.py", line 1367, in train_for_imputation_nbr_0
    self.train(
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/site-packages/higashi/Higashi_wrapper.py", line 1141, in train
    valid_bce_loss, valid_accu, valid_auc1, valid_auc2, _, _ = self.eval_epoch(validation_data_generator)
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/site-packages/higashi/Higashi_wrapper.py", line 1005, in eval_epoch
    batch_x, batch_y, batch_w, batch_chrom, batch_to_neighs, chroms_in_batch = p.result()
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/data02/home/scv9147/run/miniconda3/envs/higashi/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

How do I solve this problem?

**Comment by shu-z** [comment]
Hi, I'm having the same issue -- did you ever find a solution?
